// NOTE: this file is PARTIALLY autogenerated via: ./opcode_tab.py gen_c
#include "CpuA64/opcode_gen.h"
#include "Util/assert.h"

namespace cwerg::a64 {

struct BitRange {
  uint8_t width;
  uint8_t position;
};

struct Field {
  uint8_t num_bit_ranges;
  BitRange bit_ranges[MAX_BIT_RANGES];
};

/* @AUTOGEN-START@ */
// Indexed by OK
static const Field FieldTable[] = {
{   // Invalid = 0
    0, {
}}, 
{   // WREG_0_4 = 1
    1, {
    {5, 0},
}}, 
{   // WREG_5_9 = 2
    1, {
    {5, 5},
}}, 
{   // WREG_10_14 = 3
    1, {
    {5, 10},
}}, 
{   // WREG_16_20 = 4
    1, {
    {5, 16},
}}, 
{   // XREG_0_4 = 5
    1, {
    {5, 0},
}}, 
{   // XREG_5_9 = 6
    1, {
    {5, 5},
}}, 
{   // XREG_10_14 = 7
    1, {
    {5, 10},
}}, 
{   // XREG_16_20 = 8
    1, {
    {5, 16},
}}, 
{   // SREG_0_4 = 9
    1, {
    {5, 0},
}}, 
{   // SREG_5_9 = 10
    1, {
    {5, 5},
}}, 
{   // SREG_10_14 = 11
    1, {
    {5, 10},
}}, 
{   // SREG_16_20 = 12
    1, {
    {5, 16},
}}, 
{   // DREG_0_4 = 13
    1, {
    {5, 0},
}}, 
{   // DREG_5_9 = 14
    1, {
    {5, 5},
}}, 
{   // DREG_10_14 = 15
    1, {
    {5, 10},
}}, 
{   // DREG_16_20 = 16
    1, {
    {5, 16},
}}, 
{   // BREG_0_4 = 17
    1, {
    {5, 0},
}}, 
{   // BREG_5_9 = 18
    1, {
    {5, 5},
}}, 
{   // BREG_10_14 = 19
    1, {
    {5, 10},
}}, 
{   // BREG_16_20 = 20
    1, {
    {5, 16},
}}, 
{   // HREG_0_4 = 21
    1, {
    {5, 0},
}}, 
{   // HREG_5_9 = 22
    1, {
    {5, 5},
}}, 
{   // HREG_10_14 = 23
    1, {
    {5, 10},
}}, 
{   // HREG_16_20 = 24
    1, {
    {5, 16},
}}, 
{   // QREG_0_4 = 25
    1, {
    {5, 0},
}}, 
{   // QREG_5_9 = 26
    1, {
    {5, 5},
}}, 
{   // QREG_10_14 = 27
    1, {
    {5, 10},
}}, 
{   // QREG_16_20 = 28
    1, {
    {5, 16},
}}, 
{   // WREG_0_4_SP = 29
    1, {
    {5, 0},
}}, 
{   // WREG_5_9_SP = 30
    1, {
    {5, 5},
}}, 
{   // XREG_0_4_SP = 31
    1, {
    {5, 0},
}}, 
{   // XREG_5_9_SP = 32
    1, {
    {5, 5},
}}, 
{   // REG_LINK = 33
    0, {
}}, 
{   // SHIFT_22_23 = 34
    1, {
    {2, 22},
}}, 
{   // SHIFT_22_23_NO_ROR = 35
    1, {
    {2, 22},
}}, 
{   // SHIFT_15_W = 36
    1, {
    {1, 15},
}}, 
{   // SHIFT_15_X = 37
    1, {
    {1, 15},
}}, 
{   // SIMM_PCREL_0_25 = 38
    1, {
    {26, 0},
}}, 
{   // SIMM_12_20 = 39
    1, {
    {9, 12},
}}, 
{   // SIMM_15_21_TIMES16 = 40
    1, {
    {7, 15},
}}, 
{   // SIMM_15_21_TIMES4 = 41
    1, {
    {7, 15},
}}, 
{   // SIMM_15_21_TIMES8 = 42
    1, {
    {7, 15},
}}, 
{   // SIMM_PCREL_5_18 = 43
    1, {
    {14, 5},
}}, 
{   // SIMM_PCREL_5_23 = 44
    1, {
    {19, 5},
}}, 
{   // SIMM_PCREL_5_23_29_30 = 45
    2, {
    {19, 5},
    {2, 29},
}}, 
{   // IMM_10_12_LIMIT4 = 46
    1, {
    {3, 10},
}}, 
{   // IMM_10_15 = 47
    1, {
    {6, 10},
}}, 
{   // IMM_10_15_16_22_W = 48
    1, {
    {13, 10},
}}, 
{   // IMM_10_15_16_22_X = 49
    1, {
    {13, 10},
}}, 
{   // IMM_10_21 = 50
    1, {
    {12, 10},
}}, 
{   // IMM_SHIFTED_10_21_22 = 51
    1, {
    {13, 10},
}}, 
{   // IMM_10_21_times_16 = 52
    1, {
    {12, 10},
}}, 
{   // IMM_10_21_times_2 = 53
    1, {
    {12, 10},
}}, 
{   // IMM_10_21_times_4 = 54
    1, {
    {12, 10},
}}, 
{   // IMM_10_21_times_8 = 55
    1, {
    {12, 10},
}}, 
{   // IMM_12_MAYBE_SHIFT_0 = 56
    1, {
    {1, 12},
}}, 
{   // IMM_12_MAYBE_SHIFT_1 = 57
    1, {
    {1, 12},
}}, 
{   // IMM_12_MAYBE_SHIFT_2 = 58
    1, {
    {1, 12},
}}, 
{   // IMM_12_MAYBE_SHIFT_3 = 59
    1, {
    {1, 12},
}}, 
{   // IMM_12_MAYBE_SHIFT_4 = 60
    1, {
    {1, 12},
}}, 
{   // IMM_16_20 = 61
    1, {
    {5, 16},
}}, 
{   // IMM_16_21 = 62
    1, {
    {6, 16},
}}, 
{   // IMM_19_23_31 = 63
    2, {
    {1, 31},
    {5, 19},
}}, 
{   // IMM_5_20 = 64
    1, {
    {16, 5},
}}, 
{   // IMM_COND_0_3 = 65
    1, {
    {4, 0},
}}, 
{   // IMM_FLT_ZERO = 66
    0, {
}}, 
{   // IMM_SHIFTED_5_20_21_22 = 67
    1, {
    {18, 5},
}}, 
{   // FLT_13_20 = 68
    1, {
    {8, 13},
}}, 
};

// Indexed by djb2 hash of mnemonic. Collisions are resolved via linear probing
static const OPC MnemonicHashTable[2048] = {
   OPC::invalid, OPC::fnmadd_s, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csneg_w_pl, OPC::invalid,
   OPC::fcvtau_x_d, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fcvtau_x_s,
   OPC::invalid, OPC::ccmp_x_imm_vc, OPC::invalid, OPC::frintp_d,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmp_w_reg_cc, OPC::invalid, OPC::ldp_w_imm_post, OPC::invalid,
   OPC::sub_w_reg_uxtb, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::sub_x_imm, OPC::ccmp_x_imm_vs, OPC::sub_w_reg_uxth, OPC::frintp_s,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmp_w_reg_cs, OPC::invalid, OPC::fmin_d, OPC::invalid,
   OPC::invalid, OPC::fcvtnu_x_d, OPC::invalid, OPC::scvtf_d_from_w,
   OPC::scvtf_d_from_x, OPC::sub_w_reg_uxtw, OPC::sub_w_reg_uxtx, OPC::ccmn_w_imm_pl,
   OPC::csinv_x_pl, OPC::ldp_w_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fmin_s, OPC::invalid, OPC::invalid,
   OPC::fcvtnu_x_s, OPC::invalid, OPC::invalid, OPC::str_b_imm_pre,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::frinta_d, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ccmn_w_reg_vc, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::adds_w_reg_uxtb, OPC::invalid,
   OPC::invalid, OPC::fstp_q_imm_post, OPC::invalid, OPC::frinta_s,
   OPC::adds_w_reg_uxth, OPC::invalid, OPC::invalid, OPC::ands_x_reg,
   OPC::b_vc, OPC::dsb_ish, OPC::ccmn_w_reg_vs, OPC::eor_w_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::adds_w_reg_uxtw,
   OPC::adds_w_reg_uxtx, OPC::invalid, OPC::invalid, OPC::b_vs,
   OPC::umulh, OPC::ccmp_w_reg_eq, OPC::fldr_s_reg_w, OPC::fldr_s_reg_x,
   OPC::invalid, OPC::fcvtps_x_d, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fldr_h_imm_pre, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ldrsh_x_imm_pre, OPC::lsrv_w, OPC::sub_x_reg_sxtb,
   OPC::lsrv_x, OPC::fcvtps_x_s, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::sub_x_reg_sxth, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ldp_sw_imm_pre, OPC::subs_w_reg_uxtb,
   OPC::sub_x_reg_sxtw, OPC::sub_x_reg_sxtx, OPC::adds_w_imm, OPC::stur_b_imm,
   OPC::rev32, OPC::subs_w_reg_uxth, OPC::fccmp_s_vc, OPC::ldur_b_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csinc_w_vc,
   OPC::invalid, OPC::invalid, OPC::ccmp_w_reg_ge, OPC::invalid,
   OPC::fccmp_s_vs, OPC::invalid, OPC::invalid, OPC::fstur_q_imm,
   OPC::subs_w_reg_uxtw, OPC::subs_w_reg_uxtx, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csinc_w_vs,
   OPC::fldur_q_imm, OPC::adds_x_reg_sxtb, OPC::ccmp_w_reg_gt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::adds_x_reg_sxth,
   OPC::invalid, OPC::invalid, OPC::ldp_x_imm, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::isb,
   OPC::adc_w, OPC::adc_x, OPC::ccmp_w_imm_cc, OPC::csneg_w_vc,
   OPC::fabs_d, OPC::invalid, OPC::adds_x_reg_sxtw, OPC::adds_x_reg_sxtx,
   OPC::adrp, OPC::ccmp_w_reg_hi, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csneg_w_vs,
   OPC::fabs_s, OPC::ldp_sw_imm_post, OPC::ccmp_w_imm_cs, OPC::invalid,
   OPC::fsqrt_d, OPC::fmov_w_from_s, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::cls_w, OPC::cls_x, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::eor_x_imm, OPC::invalid, OPC::ldrsb_x_reg_w, OPC::ldrsb_x_reg_x,
   OPC::fsqrt_s, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fstr_h_imm_post, OPC::invalid,
   OPC::invalid, OPC::fabd_d, OPC::subs_x_reg_sxtb, OPC::ccmn_w_imm_vc,
   OPC::csinv_x_vc, OPC::fldr_d_imm_post, OPC::invalid, OPC::ldrsb_x_imm_pre,
   OPC::subs_x_reg_sxth, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fabd_s, OPC::fldp_s_imm_pre, OPC::ccmn_w_imm_vs, OPC::str_w_reg_w,
   OPC::str_w_reg_x, OPC::csinv_x_vs, OPC::invalid, OPC::subs_x_reg_sxtw,
   OPC::subs_x_reg_sxtx, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::orr_w_imm, OPC::invalid, OPC::invalid, OPC::sbc_w,
   OPC::sbc_x, OPC::ccmp_w_imm_eq, OPC::fstr_h_imm_pre, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::adds_x_imm, OPC::invalid,
   OPC::fstur_b_imm, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fldr_d_reg_w,
   OPC::fldr_d_reg_x, OPC::fldur_b_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fmov_s_imm, OPC::msub_w, OPC::msub_x,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::movn_w_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ldp_x_imm_post,
   OPC::invalid, OPC::sub_x_reg_uxtb, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::sub_x_reg_uxth,
   OPC::ccmp_w_imm_ge, OPC::ccmp_w_reg_le, OPC::fminnm_d, OPC::fmaxnm_d,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ccmp_w_reg_ls, OPC::sub_x_reg_uxtw, OPC::sub_x_reg_uxtx,
   OPC::ccmp_w_reg_lt, OPC::ccmp_w_imm_gt, OPC::fmaxnm_s, OPC::fminnm_s,
   OPC::invalid, OPC::add_w_reg, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::scvtf_s_from_w, OPC::scvtf_s_from_x,
   OPC::fneg_d, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmp_w_reg_mi, OPC::ccmp_w_imm_hi, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::subs_w_reg, OPC::invalid, OPC::adds_x_reg_uxtb,
   OPC::fneg_s, OPC::fcvtpu_x_d, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::adds_x_reg_uxth, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::sbfm_w,
   OPC::sbfm_x, OPC::fldr_q_imm_pre, OPC::fcvtpu_x_s, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::adds_x_reg_uxtw, OPC::adds_x_reg_uxtx, OPC::ccmp_w_reg_ne, OPC::invalid,
   OPC::invalid, OPC::orr_x_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::asrv_w,
   OPC::asrv_x, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fstp_s_imm_pre, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fmov_d_imm, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fstp_d_imm_post, OPC::fstur_s_imm, OPC::invalid, OPC::ldursh_w_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fldur_s_imm, OPC::fadd_d,
   OPC::subs_x_reg_uxtb, OPC::str_h_reg_w, OPC::str_h_reg_x, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::subs_x_reg_uxth, OPC::movn_x_imm,
   OPC::ldr_w_imm, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fadd_s, OPC::invalid,
   OPC::cbnz_w, OPC::cbnz_x, OPC::csel_x_cc, OPC::invalid,
   OPC::invalid, OPC::subs_x_reg_uxtw, OPC::subs_x_reg_uxtx, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmp_w_reg_pl, OPC::invalid,
   OPC::movk_w, OPC::movk_x, OPC::csel_x_cs, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::add_x_reg, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fldr_s_imm_post, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmp_w_imm_le, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ldr_h_imm_post, OPC::subs_x_reg, OPC::fldp_d_imm_pre,
   OPC::fldr_h_imm, OPC::invalid, OPC::fcsel_d_cc, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmp_w_imm_ls, OPC::ccmp_w_imm_lt,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fcsel_d_cs, OPC::stlr_b,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::stlr_h, OPC::invalid, OPC::invalid,
   OPC::fstp_q_imm, OPC::ccmp_w_imm_mi, OPC::invalid, OPC::invalid,
   OPC::csel_x_eq, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fstr_q_imm_pre, OPC::invalid, OPC::fstur_d_imm, OPC::invalid,
   OPC::stlr_w, OPC::stlr_x, OPC::ldxr_b, OPC::csinv_w_cc,
   OPC::frintx_d, OPC::blr, OPC::ldxr_h, OPC::fldur_d_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::and_w_reg,
   OPC::ldrsh_w_reg_w, OPC::ldrsh_w_reg_x, OPC::fstr_b_imm_post, OPC::invalid,
   OPC::ldr_w_reg_w, OPC::ldr_w_reg_x, OPC::ldr_h_imm, OPC::ldursh_x_imm,
   OPC::ccmp_w_imm_ne, OPC::ldxr_w, OPC::ldxr_x, OPC::csinv_w_cs,
   OPC::frintx_s, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ldr_x_imm, OPC::invalid, OPC::invalid, OPC::ldp_w_imm_pre,
   OPC::rorv_w, OPC::rorv_x, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::movz_w_imm, OPC::fcsel_d_eq, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csel_x_ge, OPC::invalid,
   OPC::invalid, OPC::fcvtms_w_d, OPC::invalid, OPC::invalid,
   OPC::frinti_d, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::smsubl,
   OPC::invalid, OPC::csel_x_gt, OPC::invalid, OPC::invalid,
   OPC::fcvtms_w_s, OPC::invalid, OPC::invalid, OPC::frinti_s,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csinv_w_eq,
   OPC::ldrsb_w_imm, OPC::csel_x_hi, OPC::fldr_b_imm_pre, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ccmp_w_imm_pl,
   OPC::invalid, OPC::invalid, OPC::fcvtzs_w_d, OPC::invalid,
   OPC::fcsel_d_ge, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fstp_d_imm_pre, OPC::fcvtzs_w_s, OPC::fcsel_d_gt,
   OPC::invalid, OPC::csinc_x_cc, OPC::invalid, OPC::ccmp_w_reg_vc,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::eon_w_reg, OPC::fstp_s_imm_post,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::csinc_x_cs, OPC::invalid, OPC::ands_w_imm,
   OPC::ccmp_w_reg_vs, OPC::frintz_d, OPC::fcsel_d_hi, OPC::invalid,
   OPC::invalid, OPC::csinv_w_ge, OPC::invalid, OPC::invalid,
   OPC::and_x_reg, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::csneg_x_cc, OPC::invalid, OPC::invalid,
   OPC::frintz_s, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::csinv_w_gt, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ccmn_x_reg_cc,
   OPC::invalid, OPC::csneg_x_cs, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ubfm_w, OPC::ubfm_x, OPC::fcvtas_w_d,
   OPC::invalid, OPC::invalid, OPC::movz_x_imm, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csinv_w_hi, OPC::ccmn_x_reg_cs,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fcvtas_w_s, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::stp_w_imm_pre, OPC::cbz_w,
   OPC::cbz_x, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ldr_h_reg_w, OPC::ldr_h_reg_x, OPC::csinc_x_eq,
   OPC::brk, OPC::ldr_w_imm_post, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::dsb_ishld, OPC::fcvtns_w_d, OPC::csel_x_le,
   OPC::fnmsub_d, OPC::ldrsb_x_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fstr_h_reg_w, OPC::fstr_h_reg_x,
   OPC::invalid, OPC::csneg_x_eq, OPC::csel_x_ls, OPC::tbnz,
   OPC::csel_x_lt, OPC::fnmsub_s, OPC::fcvtns_w_s, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fstr_b_imm_pre, OPC::invalid, OPC::ccmn_x_reg_eq,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fstp_s_imm, OPC::csinc_x_ge,
   OPC::csel_x_mi, OPC::invalid, OPC::invalid, OPC::eon_x_reg,
   OPC::fstr_q_imm_post, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ands_x_imm, OPC::fcsel_d_le, OPC::csinc_x_gt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::stur_w_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ldr_b_imm_post,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fcsel_d_ls,
   OPC::ldur_w_imm, OPC::csel_x_ne, OPC::fcsel_d_lt, OPC::csneg_x_ge,
   OPC::ccmp_w_imm_vc, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::csinc_x_hi, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::add_w_reg_sxtb, OPC::invalid, OPC::invalid,
   OPC::ldp_x_imm_pre, OPC::ccmn_x_reg_ge, OPC::csneg_x_gt, OPC::orn_w_reg,
   OPC::add_w_reg_sxth, OPC::ccmp_w_imm_vs, OPC::fcsel_d_mi, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csinv_w_le, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fcvtmu_w_d,
   OPC::ccmn_x_reg_gt, OPC::invalid, OPC::add_w_reg_sxtw, OPC::add_w_reg_sxtx,
   OPC::frintm_d, OPC::ldrsw_imm_pre, OPC::invalid, OPC::invalid,
   OPC::csinv_w_ls, OPC::csinv_w_lt, OPC::csneg_x_hi, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fcvtmu_w_s, OPC::invalid,
   OPC::ccmn_x_imm_cc, OPC::invalid, OPC::invalid, OPC::frintm_s,
   OPC::fcsel_d_ne, OPC::invalid, OPC::ccmn_x_reg_hi, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csinv_w_mi,
   OPC::ccmn_x_imm_cs, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ucvtf_d_from_w, OPC::smaddl, OPC::ucvtf_d_from_x,
   OPC::invalid, OPC::invalid, OPC::csel_x_pl, OPC::invalid,
   OPC::fcvtzu_w_d, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fstp_d_imm,
   OPC::fldr_s_imm_pre, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fcvtzu_w_s,
   OPC::csinv_w_ne, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::adcs_w, OPC::adcs_x,
   OPC::fstr_q_imm, OPC::stp_w_imm_post, OPC::invalid, OPC::invalid,
   OPC::stur_h_imm, OPC::umsubl, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fmadd_d, OPC::ldur_h_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fcsel_s_cc, OPC::invalid, OPC::invalid,
   OPC::stur_x_imm, OPC::hlt, OPC::invalid, OPC::invalid,
   OPC::fcsel_d_pl, OPC::svc, OPC::invalid, OPC::fmadd_s,
   OPC::ccmn_x_imm_eq, OPC::ldur_x_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fcsel_s_cs, OPC::invalid, OPC::invalid,
   OPC::csinc_x_le, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ldrsw_reg_w, OPC::ldrsw_reg_x, OPC::invalid, OPC::fcvtau_w_d,
   OPC::orn_x_reg, OPC::invalid, OPC::csinc_x_ls, OPC::csinc_x_lt,
   OPC::rbit_w, OPC::rbit_x, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fcvtau_w_s, OPC::invalid,
   OPC::invalid, OPC::csinv_w_pl, OPC::invalid, OPC::stp_x_imm_pre,
   OPC::csneg_x_le, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::csinc_x_mi, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::dsb_ishst, OPC::invalid, OPC::csneg_x_ls, OPC::ccmn_x_imm_ge,
   OPC::csneg_x_lt, OPC::ccmn_x_reg_le, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fcvtnu_w_d, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ldrsw_imm_post, OPC::ccmn_x_reg_ls, OPC::ccmn_x_reg_lt, OPC::ccmn_x_imm_gt,
   OPC::fcsel_s_eq, OPC::invalid, OPC::csinc_x_ne, OPC::invalid,
   OPC::invalid, OPC::csneg_x_mi, OPC::invalid, OPC::add_w_reg_uxtb,
   OPC::fcvtnu_w_s, OPC::ldr_x_imm_post, OPC::invalid, OPC::fstr_b_imm,
   OPC::invalid, OPC::add_w_reg_uxth, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ccmn_x_reg_mi,
   OPC::ccmn_x_imm_hi, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::add_w_reg_uxtw, OPC::add_w_reg_uxtx, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csneg_x_ne, OPC::fstr_s_imm_pre,
   OPC::invalid, OPC::invalid, OPC::fstur_h_imm, OPC::invalid,
   OPC::invalid, OPC::ldrsb_w_reg_w, OPC::add_w_imm, OPC::ldrsb_w_reg_x,
   OPC::fldr_h_reg_w, OPC::fldr_h_reg_x, OPC::fmov_d_from_x, OPC::fldur_h_imm,
   OPC::ccmn_x_reg_ne, OPC::invalid, OPC::invalid, OPC::fcsel_s_ge,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fcvtps_w_d, OPC::eret, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::subs_w_imm, OPC::csel_x_vc,
   OPC::fmul_d, OPC::invalid, OPC::fcsel_s_gt, OPC::invalid,
   OPC::invalid, OPC::str_b_imm, OPC::invalid, OPC::fcvtps_w_s,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csinc_x_pl,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csel_x_vs,
   OPC::fmul_s, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fcsel_s_hi, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::add_x_reg_sxtb, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::csneg_x_pl,
   OPC::add_x_reg_sxth, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fcsel_d_vc, OPC::fstr_d_imm_post, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ccmn_x_reg_pl, OPC::fccmp_d_cc, OPC::add_x_reg_sxtw,
   OPC::add_x_reg_sxtx, OPC::fldr_d_imm_pre, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fcsel_d_vs, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fccmp_d_cs, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ccmn_x_imm_le,
   OPC::bfm_w, OPC::bfm_x, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csinv_w_vc, OPC::invalid,
   OPC::fstr_s_imm, OPC::fcmgt_d, OPC::invalid, OPC::dmb_ish,
   OPC::invalid, OPC::ccmn_x_imm_ls, OPC::ccmn_x_imm_lt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csinv_w_vs, OPC::add_x_imm,
   OPC::fcmgt_s, OPC::ucvtf_s_from_w, OPC::ucvtf_s_from_x, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmn_x_imm_mi, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fsub_d, OPC::ldrsb_w_imm_post, OPC::stp_x_imm_post, OPC::subs_x_imm,
   OPC::umaddl, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ldr_w_imm_pre, OPC::fccmp_d_eq, OPC::fsub_s,
   OPC::invalid, OPC::invalid, OPC::fcmge_d, OPC::invalid,
   OPC::invalid, OPC::fcmp_d_zero, OPC::fcvt_s_d, OPC::invalid,
   OPC::invalid, OPC::ccmn_x_imm_ne, OPC::fcvt_s_h, OPC::invalid,
   OPC::fcsel_s_le, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fcmge_s, OPC::invalid, OPC::invalid,
   OPC::adr, OPC::yield, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::sub_w_reg, OPC::fldp_q_imm_post,
   OPC::fcsel_s_ls, OPC::fcsel_s_lt, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::and_w_imm, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fcsel_s_mi, OPC::invalid, OPC::invalid,
   OPC::fccmp_d_ge, OPC::fldp_q_imm, OPC::invalid, OPC::ldrsh_w_imm_post,
   OPC::invalid, OPC::ccmp_x_reg_cc, OPC::fcvt_d_h, OPC::invalid,
   OPC::csinc_x_vc, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fstr_d_imm, OPC::invalid, OPC::fccmp_d_gt,
   OPC::invalid, OPC::fcvt_d_s, OPC::invalid, OPC::fstr_d_imm_pre,
   OPC::ldp_sw_imm, OPC::ccmp_x_reg_cs, OPC::invalid, OPC::invalid,
   OPC::csinc_x_vs, OPC::invalid, OPC::fcsel_s_ne, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmn_x_imm_pl, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fccmp_d_hi, OPC::invalid, OPC::invalid,
   OPC::add_x_reg_uxtb, OPC::csneg_x_vc, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ldursb_w_imm, OPC::add_x_reg_uxth, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fcmp_d, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::str_b_reg_w, OPC::str_b_reg_x,
   OPC::csneg_x_vs, OPC::ccmn_x_reg_vc, OPC::fcvtpu_w_d, OPC::invalid,
   OPC::invalid, OPC::add_x_reg_uxtw, OPC::add_x_reg_uxtx, OPC::invalid,
   OPC::invalid, OPC::fcmp_s, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmn_x_reg_vs, OPC::invalid,
   OPC::invalid, OPC::fcvtpu_w_s, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ret, OPC::ccmp_x_reg_eq, OPC::invalid, OPC::invalid,
   OPC::stp_w_imm, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fmov_s_from_w, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::str_w_imm_pre, OPC::fstr_s_imm_post, OPC::invalid, OPC::fcsel_s_pl,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::sub_x_reg,
   OPC::clrex, OPC::invalid, OPC::invalid, OPC::csel_w_cc,
   OPC::invalid, OPC::ldar_b, OPC::invalid, OPC::invalid,
   OPC::str_h_imm_post, OPC::invalid, OPC::invalid, OPC::ldar_h,
   OPC::invalid, OPC::and_x_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::tbz, OPC::invalid, OPC::csel_w_cs,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fldr_h_imm_post,
   OPC::invalid, OPC::invalid, OPC::ldar_w, OPC::ldar_x,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ccmp_x_reg_ge,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::nop, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmp_x_reg_gt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::eor_w_reg, OPC::invalid,
   OPC::invalid, OPC::ldaxr_b, OPC::fccmp_d_le, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmp_x_imm_cc, OPC::ldaxr_h,
   OPC::invalid, OPC::invalid, OPC::ldursb_x_imm, OPC::dmb_ishld,
   OPC::ccmp_x_reg_hi, OPC::fmov_x_from_d, OPC::invalid, OPC::fccmp_d_ls,
   OPC::fccmp_d_lt, OPC::fdiv_d, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ldaxr_w, OPC::ldaxr_x,
   OPC::ldr_h_imm_pre, OPC::csel_w_eq, OPC::ccmp_x_imm_cs, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fdiv_s, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ldr_x_imm_pre, OPC::fccmp_d_mi,
   OPC::str_x_reg_w, OPC::str_x_reg_x, OPC::fstr_q_reg_w, OPC::fstr_q_reg_x,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::adds_w_reg, OPC::stp_x_imm, OPC::invalid, OPC::ccmn_x_imm_vc,
   OPC::invalid, OPC::invalid, OPC::ldrsb_x_imm_post, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmn_w_reg_cc, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fccmp_d_ne,
   OPC::invalid, OPC::invalid, OPC::sbcs_w, OPC::sbcs_x,
   OPC::ccmn_x_imm_vs, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::b_cc, OPC::csel_w_ge, OPC::ccmn_w_reg_cs, OPC::invalid,
   OPC::invalid, OPC::sdiv_w, OPC::sdiv_x, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmp_x_imm_eq, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::b_cs, OPC::csel_w_gt, OPC::invalid, OPC::fldp_s_imm,
   OPC::invalid, OPC::invalid, OPC::fcvt_h_d, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::bic_w_reg, OPC::b,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fcvt_h_s, OPC::csel_w_hi, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fcsel_s_vc, OPC::invalid, OPC::invalid, OPC::eor_x_reg,
   OPC::ldrsh_x_imm_post, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fccmp_s_cc, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmp_x_imm_ge, OPC::ccmp_x_reg_le, OPC::ccmn_w_reg_eq, OPC::fcsel_s_vs,
   OPC::csinc_w_cc, OPC::madd_w, OPC::madd_x, OPC::fccmp_d_pl,
   OPC::invalid, OPC::fldp_d_imm_post, OPC::fccmp_s_cs, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmp_x_reg_ls, OPC::ccmp_x_reg_lt,
   OPC::b_eq, OPC::lslv_w, OPC::lslv_x, OPC::ccmp_x_imm_gt,
   OPC::csinc_w_cs, OPC::fcmp_s_zero, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::orr_w_reg,
   OPC::invalid, OPC::str_h_imm_pre, OPC::invalid, OPC::invalid,
   OPC::csneg_w_cc, OPC::ccmp_x_reg_mi, OPC::ccmp_x_imm_hi, OPC::ldrsw_imm,
   OPC::invalid, OPC::adds_x_reg, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::str_w_imm_post,
   OPC::ldr_b_reg_w, OPC::str_x_imm_pre, OPC::extr_w, OPC::extr_x,
   OPC::ldr_b_reg_x, OPC::csneg_w_cs, OPC::invalid, OPC::invalid,
   OPC::ccmn_w_reg_ge, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmp_x_reg_ne, OPC::invalid,
   OPC::fldp_d_imm, OPC::invalid, OPC::b_ge, OPC::ccmn_w_reg_gt,
   OPC::invalid, OPC::fccmp_s_eq, OPC::invalid, OPC::invalid,
   OPC::fstr_b_reg_w, OPC::fstr_b_reg_x, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fldr_q_imm,
   OPC::csinc_w_eq, OPC::b_gt, OPC::invalid, OPC::stlxr_b,
   OPC::ccmn_w_imm_cc, OPC::csinv_x_cc, OPC::invalid, OPC::bic_x_reg,
   OPC::rev_w, OPC::stlxr_h, OPC::ccmn_w_reg_hi, OPC::rev_x,
   OPC::invalid, OPC::ldursw_imm_post, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csel_w_le, OPC::ccmn_w_imm_cs,
   OPC::csinv_x_cs, OPC::fcvtms_x_d, OPC::invalid, OPC::stxr_b,
   OPC::stlxr_w, OPC::stlxr_x, OPC::b_hi, OPC::invalid,
   OPC::invalid, OPC::stxr_h, OPC::invalid, OPC::invalid,
   OPC::csneg_w_eq, OPC::csel_w_ls, OPC::dmb_ishst, OPC::csel_w_lt,
   OPC::clz_w, OPC::clz_x, OPC::str_b_imm_post, OPC::fmsub_d,
   OPC::fcvtms_x_s, OPC::invalid, OPC::invalid, OPC::fccmp_s_ge,
   OPC::stxr_w, OPC::stxr_x, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fmsub_s, OPC::fldr_b_imm_post, OPC::csinc_w_ge, OPC::csel_w_mi,
   OPC::ccmp_x_reg_pl, OPC::invalid, OPC::fccmp_s_gt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fcvtzs_x_d,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::csinc_w_gt, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fnmul_d, OPC::invalid,
   OPC::orr_x_reg, OPC::invalid, OPC::fcvtzs_x_s, OPC::invalid,
   OPC::fccmp_s_hi, OPC::ccmp_x_imm_le, OPC::invalid, OPC::ccmn_w_imm_eq,
   OPC::csel_w_ne, OPC::csinv_x_eq, OPC::str_w_imm, OPC::csneg_w_ge,
   OPC::invalid, OPC::fnmul_s, OPC::invalid, OPC::csinc_w_hi,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ccmp_x_imm_ls,
   OPC::ccmp_x_imm_lt, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::csneg_w_gt, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::fccmp_d_vc, OPC::invalid, OPC::invalid,
   OPC::ldrsh_x_reg_w, OPC::ldrsh_x_reg_x, OPC::invalid, OPC::invalid,
   OPC::fldr_b_imm, OPC::ldr_x_reg_w, OPC::ldr_x_reg_x, OPC::fldr_q_reg_w,
   OPC::fldr_q_reg_x, OPC::invalid, OPC::ccmp_x_imm_mi, OPC::invalid,
   OPC::invalid, OPC::fccmp_d_vs, OPC::ldrsh_w_imm, OPC::csneg_w_hi,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::fldp_q_imm_pre,
   OPC::invalid, OPC::invalid, OPC::fcvtas_x_d, OPC::invalid,
   OPC::invalid, OPC::ccmn_w_imm_ge, OPC::ccmn_w_reg_le, OPC::csinv_x_ge,
   OPC::invalid, OPC::fstr_h_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::ccmp_x_imm_ne,
   OPC::invalid, OPC::fcvtas_x_s, OPC::invalid, OPC::b_le,
   OPC::ccmn_w_reg_ls, OPC::bics_w_reg, OPC::ccmn_w_reg_lt, OPC::ccmn_w_imm_gt,
   OPC::csinv_x_gt, OPC::csel_w_pl, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fldp_s_imm_post, OPC::b_ls, OPC::b_lt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ldr_b_imm, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmn_w_reg_mi, OPC::ccmn_w_imm_hi,
   OPC::csinv_x_hi, OPC::invalid, OPC::invalid, OPC::udiv_w,
   OPC::udiv_x, OPC::fcvtns_x_d, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::b_mi, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fcvtns_x_s, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::str_h_imm,
   OPC::invalid, OPC::fstr_s_reg_w, OPC::fstr_s_reg_x, OPC::ccmn_w_reg_ne,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::rev16_w,
   OPC::rev16_x, OPC::fccmp_s_le, OPC::invalid, OPC::bl,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::str_x_imm,
   OPC::invalid, OPC::br, OPC::b_ne, OPC::csinc_w_le,
   OPC::ccmp_x_imm_pl, OPC::invalid, OPC::fccmp_s_ls, OPC::fccmp_s_lt,
   OPC::invalid, OPC::invalid, OPC::sub_w_reg_sxtb, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::sub_w_reg_sxth, OPC::csinc_w_ls, OPC::csinc_w_lt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::smulh, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmp_x_reg_vc, OPC::fccmp_s_mi, OPC::invalid, OPC::sub_w_reg_sxtw,
   OPC::sub_w_reg_sxtx, OPC::invalid, OPC::invalid, OPC::ldrsh_x_imm,
   OPC::str_x_imm_post, OPC::csneg_w_le, OPC::invalid, OPC::invalid,
   OPC::ldrsh_w_imm_pre, OPC::csinc_w_mi, OPC::fldr_s_imm, OPC::invalid,
   OPC::ccmp_x_reg_vs, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::csneg_w_ls, OPC::csneg_w_lt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::fccmp_s_ne, OPC::invalid,
   OPC::adds_w_reg_sxtb, OPC::ccmn_w_reg_pl, OPC::fcvtmu_x_d, OPC::invalid,
   OPC::invalid, OPC::frintn_d, OPC::adds_w_reg_sxth, OPC::bics_x_reg,
   OPC::fstp_q_imm_pre, OPC::csinc_w_ne, OPC::invalid, OPC::invalid,
   OPC::csneg_w_mi, OPC::fldr_b_reg_w, OPC::b_pl, OPC::fldr_b_reg_x,
   OPC::fldr_q_imm_post, OPC::fcvtmu_x_s, OPC::invalid, OPC::sub_w_imm,
   OPC::frintn_s, OPC::adds_w_reg_sxtw, OPC::adds_w_reg_sxtx, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ccmn_w_imm_le, OPC::csinv_x_le,
   OPC::ldr_b_imm_pre, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fmax_d, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmn_w_imm_ls, OPC::csneg_w_ne, OPC::ccmn_w_imm_lt, OPC::csinv_x_ls,
   OPC::csinv_x_lt, OPC::fcvtzu_x_d, OPC::invalid, OPC::fmax_s,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::fcvtzu_x_s, OPC::invalid, OPC::invalid, OPC::ccmn_w_imm_mi,
   OPC::csinv_x_mi, OPC::subs_w_reg_sxtb, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csel_w_vc, OPC::subs_w_reg_sxth,
   OPC::fccmp_s_pl, OPC::invalid, OPC::ands_w_reg, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::csinc_w_pl, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::subs_w_reg_sxtw, OPC::subs_w_reg_sxtx,
   OPC::csel_w_vs, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ccmn_w_imm_ne, OPC::csinv_x_ne, OPC::fnmadd_d, OPC::fldr_d_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::ldrsb_w_imm_pre, OPC::fstr_d_reg_w,
   OPC::fstr_d_reg_x, OPC::invalid, OPC::invalid, OPC::invalid,
};


const char* const SHIFT_ToStringMap[] = {
    "lsl", // 0
    "lsr", // 1
    "asr", // 2
    "ror", // 3
};

template<>  // template specialization for SHIFT
const char* EnumToString<SHIFT>(SHIFT x) { return SHIFT_ToStringMap[unsigned(x)]; }

/* @AUTOGEN-END@ */

const Opcode* FindArmOpcode(uint32_t bit_value) {
  uint32_t discriminant = (bit_value & 0x0e000000) >> 25;
  const int start = OpcodeTableJumper[2 * discriminant];
  const int end = OpcodeTableJumper[2 * discriminant + 1];
  if (start >= 0) {
    for (int i = start; i <= end; ++i) {
      const struct Opcode* opc = &OpcodeTable[i];
      if ((opc->bit_mask & bit_value) == opc->bit_value) {
        return opc;
      }
    }
  }
  return nullptr;
}

uint32_t DecodeRotatedImm(uint32_t data) {
  uint32_t x = data & 0xff;
  uint32_t rot = (data & 0xf00) >> 7;
  uint32_t mask = (1 << rot) - 1;
  return (x >> rot) | ((x & mask) << (32 - rot));
}

// Inverse of DecodeRotatedImm()
// returns -1 in case of failure
uint32_t EncodeRotatedImm(int32_t immediate) {
  uint32_t x = immediate;
  for (int r = 0; r < 16; ++r) {
    if ((x & 0xff) == x) {
      return (r << 8) | x;
    }
    // rotate left by 2
    x = (x << 2) | (x >> 30);
  }
  return kEncodeFailure;
}

uint32_t ExtractOperand(uint32_t data, OK field_kind) {
  const BitRange* bit_ranges = FieldTable[uint8_t(field_kind)].bit_ranges;

  int32_t out = 0;
  for (unsigned i = 0; i < FieldTable[uint8_t(field_kind)].num_bit_ranges;
       ++i) {
    const BitRange* range = bit_ranges + i;
    uint32_t mask = (1 << range->width) - 1;
    uint32_t x = (data >> range->position) & mask;
    out = x | out << range->width;
  }
  return out;
}

int32_t DecodeOperand(uint32_t data, OK ok) {
  switch (ok) {
    case OK::IMM_0_7_8_11:
      return DecodeRotatedImm(data);
    case OK::SIMM_0_23:
      return SignedIntFromBits(data, 24);
    case OK::IMM_ZERO:
      return 0;
    case OK::IMM_10_11_TIMES_8:
      return data * 8;
    case OK::IMM_0_7_TIMES_4:
      return data * 4;
    default:
      return data;
  }
}


uint32_t EncodeOperand(int32_t data, OK ok) {
  switch (ok) {
    case OK::IMM_0_7_8_11:
      return EncodeRotatedImm(data);
    case OK::SIMM_0_23:
      return data & 0xffffff;
    case OK::IMM_ZERO:
      return 0;
    case OK::IMM_10_11_TIMES_8:
      return data / 8;
    case OK::IMM_0_7_TIMES_4:
      return data / 4;
    default:
      return data;
  }
}

void InsertOperand(int32_t x,
                   const Field* field,
                   uint32_t* bits_value,
                   uint32_t* bits_mask) {
  const BitRange* bit_ranges = field->bit_ranges;
  // backwards is important
  for (int i = field->num_bit_ranges - 1; i >= 0; --i) {
    const BitRange* range = bit_ranges + i;
    const uint32_t mask = (1 << range->width) - 1;
    ASSERT(((mask << range->position) & *bits_mask) == 0, "");
    *bits_mask |= mask << range->position;
    *bits_value |= (x & mask) << range->position;
    x >>= range->width;
  }
}

bool Disassemble(Ins* ins, uint32_t data) {
  const struct Opcode* opcode = FindArmOpcode(data);
  if (opcode == nullptr) return false;

  ins->opcode = opcode;
  for (unsigned i = 0; i < opcode->num_fields; ++i) {
    ins->operands[i] =
        DecodeOperand(ExtractOperand(data, opcode->fields[i]),
                      opcode->fields[i]);
  }
  return true;
}

uint32_t Assemble(const Ins& ins) {
  const Opcode* opcode = ins.opcode;
  uint32_t value = opcode->bit_value;
  uint32_t mask = opcode->bit_mask;
  for (unsigned i = 0; i < opcode->num_fields; ++i) {
    const OK kind = ins.opcode->fields[i];
    ASSERT(kind != OK::Invalid, "");
    uint32_t x = EncodeOperand(ins.operands[i], kind);
    InsertOperand(x, &FieldTable[uint8_t(kind)], &value, &mask);
  }
  ASSERT(mask == 0xffffffff, "problems encoding " << opcode->name);
  return value;
}

uint32_t PatchIns(uint32_t ins_old, unsigned pos, int32_t value) {
  Ins ins;
  CHECK(DecodeIns(&ins, ins_old), "");

  ins.operands[pos] = value;
  return EncodeIns(ins);
}

const Opcode* FindOpcodeForMnemonic(std::string_view s) {
  uint32_t h = 5381;
  for (uint8_t c : s) {
    h = (h << 5) + h + c;
  }
  h &= 0xffff;

  for (uint32_t d = 0; d < 512; ++d) {
    OPC opc = MnemonicHashTable[(h + d) % 512];
    if (opc == OPC::invalid) return nullptr;
    auto* opcode = &OpcodeTable[uint32_t(opc)];
    if (opcode->enum_name == s) return opcode;
  }
  return nullptr;
}

int32_t SignedIntFromBits(uint32_t data, unsigned n_bits) {
  uint32_t mask = (1 << n_bits) - 1;
  data &= mask;
  bool is_neg = data & (1 << (n_bits - 1));
  return is_neg ? data - (1 << n_bits) : data;
}

}  // namespace cwerg::a32
