# Prepend this to cwerg IR code before running it through CodeGenC/codegen.py
.fun exit BUILTIN [] = [U32]
.fun brk BUILTIN [A32] = [A32]
.fun open BUILTIN [S32] = [A32 S32 S32]
.fun close BUILTIN [S32] = [S32]
.fun write BUILTIN [S32] = [S32 A32 U32]
.fun read BUILTIN [S32] = [S32 A32 U32]
.fun lseek BUILTIN [S32] = [S32 S32 S32]
.fun putchar BUILTIN [] = [U8]
.fun writeln BUILTIN [] = [A32 U32]
.fun puts BUILTIN [] = [A32]
.fun print_num BUILTIN [] = [U32]
.fun print_num_ln BUILTIN [] = [U32]
.fun print_hex_num BUILTIN [] = [U32]
.fun print_hex_num_ln BUILTIN [] = [U32]
.fun free BUILTIN [] = [A32]
.fun malloc BUILTIN [A32] = [U32]
