# Prepend this to cwerg IR code before running it through CodeGenC/codegen.py

.fun exit BUILTIN [] = [U32]
.fun brk BUILTIN [A64] = [A64]
.fun open BUILTIN [S32] = [A64 S32 S32]
.fun close BUILTIN [S32] = [S32]
.fun write BUILTIN [S64] = [S32 A64 U64]
.fun read BUILTIN [S64] = [S32 A64 U64]
.fun lseek BUILTIN [S64] = [S32 S64 S32]
.fun putchar BUILTIN [] = [U8]
.fun writeln BUILTIN [] = [A64 U32]
.fun puts BUILTIN [] = [A64]
.fun print_num BUILTIN [] = [U32]
.fun print_num_ln BUILTIN [] = [U32]
.fun print_hex_num BUILTIN [] = [U32]
.fun print_hex_num_ln BUILTIN [] = [U32]
.fun free BUILTIN [] = [A64]
.fun malloc BUILTIN [A64] = [U64]
