# This Dockerfile creates a container for the runtime environment for Cwerg.
#
# To build the docker image, run the following from the Cwerg directory:
#   docker build -t cwerg-runtime-env -f docker/Dockerfile.runtime-env .
#
# To base it on a different distro, override BASEIMGAE, e.g., add:
#   --build-arg BASEIMAGE=ubuntu:25.10
#
# To use this runtime environment, run the following from the Cwerg directory:
#   docker run -it --rm -v .:/sources cwerg-runtime-env
# Then you can use the cwerg compiler on source files mounted from your host:
#   cwerg.py sources/hello_world_test.cw hello.exe

#############################################################################
# Build the C++ version of the compiler.
#############################################################################
ARG BUILD_ENV=cwerg-dev-env
ARG BASEIMAGE=alpine:3.23

FROM ${BUILD_ENV} AS builder

COPY . /Cwerg
WORKDIR /Cwerg

RUN  <<EO_RUN
  set -ex

  # Remove remnants from what we've copied in.
  make clean
  # Build the compiler executables.
  make build_compiler
  # For now the executables are: build/*.exe.
  # Ideally there would be a `make install` that could be pointed to a
  # destination directory where all necessary pieces end up and from where they
  # can be copied into a `runtime` container, e.g.,
  #   make install DESTDIR=/Cwerg-install
EO_RUN

#############################################################################
# Create intermediate image to clean up installation directories.
#############################################################################
ARG BASEIMAGE

FROM ${BASEIMAGE} AS installer

RUN  <<EO_RUN
  set -ex

  # Prepare installation location.
  for dir in FE BE IR Util build; do
    mkdir -p "/usr/local/cwerg/${dir}"
  done
EO_RUN

# Install the compiler built in the previous step.
COPY --from=builder /Cwerg/build/*.exe /usr/local/cwerg/build
# Install the compiler driver.
COPY --from=builder /Cwerg/cwerg.py /usr/local/cwerg
# Install the compiler python version.
# This copies a lot of C++ etc. junk that we don't need at runtime.
COPY --from=builder /Cwerg/FE /usr/local/cwerg/FE
COPY --from=builder /Cwerg/BE /usr/local/cwerg/BE
COPY --from=builder /Cwerg/IR /usr/local/cwerg/IR
COPY --from=builder /Cwerg/Util /usr/local/cwerg/Util

# Clean up the mess from the COPY commands above.
RUN  <<EO_RUN
  set -ex

  find /usr/local/cwerg -name "*.h" -exec rm {} +
  find /usr/local/cwerg -name "*.cc" -exec rm {} +
  find /usr/local/cwerg -name "*.md" -exec rm {} +
  find /usr/local/cwerg -name "Makefile*" -exec rm {} +
  find /usr/local/cwerg -name "*Test*" -exec rm -rf {} +
  find /usr/local/cwerg -name "Docs" -exec rm -rf {} +
EO_RUN

#############################################################################
# Create a runtime environment for the Cwerg compiler.
#############################################################################
ARG BASEIMAGE

FROM ${BASEIMAGE}

# hadolint ignore=DL3008,DL3018  # Pin versions in apt/apk.
RUN  <<EO_RUN
  set -ex

  if grep -q "ID=alpine" /etc/os-release; then 
    apk add --update --no-cache python3
    # Only /usr/bin/env is present by default, but cwerg uses /bin/env.
    ln -s /bin/busybox /bin/env
  else
    # Ubuntu and friends.
    apt-get update
    apt-get install -y --no-install-recommends python3
  
    # Clean up apt installation caches and unnecessary packages.
    apt-get autoremove -y
    rm -rf /var/lib/apt/lists/*
    apt-get clean
  fi

  # Prepare installation location for compiler.
  mkdir -p /usr/local/cwerg
EO_RUN

# Install the compiler.
COPY --from=installer /usr/local/cwerg /usr/local/cwerg
#COPY --from=builder /Cwerg-install/* /usr/local

ENV PATH="/usr/local/cwerg:$PATH"

# Image metadata.
ARG IMAGE_VERSION=unknown
LABEL \
  org.opencontainers.image.name="cwerg-runtime-env" \
  org.opencontainers.image.description="Cwerg Runtime Environment" \
  org.opencontainers.image.version="${IMAGE_VERSION}" \
  org.opencontainers.image.url="https://github.com/RobertMuth/Cwerg" \
  org.opencontainers.image.source="https://github.com/RobertMuth/Cwerg"
