// NOTE: this file is PARTIALLY autogenerated via: ./opcode_tab.py gen_c
#include "CpuA32/opcode_gen.h"
#include "Util/assert.h"

namespace cwerg::a32 {

struct BitRange {
  BitRangeKind modifier;
  uint8_t width;
  uint8_t position;
};

struct Field {
  uint8_t num_bit_ranges;
  BitRange bit_ranges[MAX_BIT_RANGES];
};

/* @AUTOGEN-START@ */
// Indexed by OPC which in turn are organize to help with disassembly
const Opcode OpcodeTable[] = {
{"invalid", "invalid", 0, 0, 0, {}, 0, MEM_WIDTH::NA, SR_UPDATE::NONE},
/* ============================================================*/
/* BLOCK 00000000 */
/* ============================================================*/
{"mul", "mul", 0x0ff0f0f0, 0x00000090,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 MUL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"mla", "mla", 0x0ff000f0, 0x00200090,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11, OK::REG_12_15},
 MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"umull", "umull", 0x0ff000f0, 0x00800090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 DST_0_1 | MUL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"umlal", "umlal", 0x0ff000f0, 0x00a00090,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_12_15, OK::REG_0_3, OK::REG_8_11},
 DST_0_1 | MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smull", "smull", 0x0ff000f0, 0x00c00090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 RESULT_64BIT | SRC_DST_0_1 | MUL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smlal", "smlal", 0x0ff000f0, 0x00e00090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 DST_0_1 | MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"muls", "muls", 0x0ff0f0f0, 0x00100090,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 MUL, MEM_WIDTH::NA, SR_UPDATE::NZ
},
{"mlas", "mlas", 0x0ff000f0, 0x00300090,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11, OK::REG_12_15},
 MULACC, MEM_WIDTH::NA, SR_UPDATE::NZ
},
{"umulls", "umulls", 0x0ff000f0, 0x00900090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 DST_0_1 | MUL, MEM_WIDTH::NA, SR_UPDATE::NZ
},
{"umlals", "umlals", 0x0ff000f0, 0x00b00090,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_12_15, OK::REG_0_3, OK::REG_8_11},
 DST_0_1 | MULACC, MEM_WIDTH::NA, SR_UPDATE::NZ
},
{"smulls", "smulls", 0x0ff000f0, 0x00d00090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 RESULT_64BIT | SRC_DST_0_1 | MUL, MEM_WIDTH::NA, SR_UPDATE::NZ
},
{"smlals", "smlals", 0x0ff000f0, 0x00f00090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 DST_0_1 | MULACC, MEM_WIDTH::NA, SR_UPDATE::NZ
},
{"mls", "mls", 0x0ff000f0, 0x00600090,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11, OK::REG_12_15},
 MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smlabb", "smlabb", 0x0ff000f0, 0x01000080,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11, OK::REG_12_15},
 MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smulbb", "smulbb", 0x0ff0f0f0, 0x01600080,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 MUL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smlatb", "smlatb", 0x0ff000f0, 0x010000a0,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11, OK::REG_12_15},
 MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smultb", "smultb", 0x0ff0f0f0, 0x016000a0,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 MUL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smlabt", "smlabt", 0x0ff000f0, 0x010000c0,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11, OK::REG_12_15},
 MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smulbt", "smulbt", 0x0ff0f0f0, 0x016000c0,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 MUL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smlatt", "smlatt", 0x0ff000f0, 0x010000e0,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11, OK::REG_12_15},
 MULACC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"smultt", "smultt", 0x0ff0f0f0, 0x016000e0,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 MUL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"strex", "strex", 0x0ff00ff0, 0x01800f90,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_0_3, OK::ADDR_BASE_ONLY, OK::REG_16_19},
 STORE | ATOMIC, MEM_WIDTH::W4, SR_UPDATE::NONE
},
{"ldrex", "ldrex", 0x0ff00fff, 0x01900f9f,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_ONLY, OK::REG_16_19},
 LOAD | ATOMIC, MEM_WIDTH::W4, SR_UPDATE::NONE
},
{"ldrh", "ldrh_imm", 0x0e5000f0, 0x005000b0,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_3_8_11},
 LOAD, MEM_WIDTH::W2, SR_UPDATE::NONE
},
{"ldrsb", "ldrsb_imm", 0x0e5000f0, 0x005000d0,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_3_8_11},
 LOAD, MEM_WIDTH::W1, SR_UPDATE::NONE
},
{"ldrsh", "ldrsh_imm", 0x0e5000f0, 0x005000f0,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_3_8_11},
 LOAD, MEM_WIDTH::W2, SR_UPDATE::NONE
},
{"strh", "strh_imm", 0x0e5000f0, 0x004000b0,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_3_8_11, OK::REG_12_15},
 STORE, MEM_WIDTH::W2, SR_UPDATE::NONE
},
{"ldrd", "ldrd_imm", 0x0e5000f0, 0x004000d0,
 5, {OK::PRED_28_31, OK::REG_PAIR_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_3_8_11},
 LOAD, MEM_WIDTH::W8, SR_UPDATE::NONE
},
{"strd", "strd_imm", 0x0e5000f0, 0x004000f0,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_3_8_11, OK::REG_PAIR_12_15},
 STORE, MEM_WIDTH::W8, SR_UPDATE::NONE
},
{"ldrh", "ldrh_reg", 0x0e500ff0, 0x001000b0,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::REG_0_3},
 LOAD, MEM_WIDTH::W2, SR_UPDATE::NONE
},
{"ldrsb", "ldrsb_reg", 0x0e500ff0, 0x001000d0,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::REG_0_3},
 LOAD, MEM_WIDTH::W1, SR_UPDATE::NONE
},
{"ldrsh", "ldrsh_reg", 0x0e500ff0, 0x001000f0,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::REG_0_3},
 LOAD, MEM_WIDTH::W2, SR_UPDATE::NONE
},
{"strh", "strh_reg", 0x0e500ff0, 0x000000b0,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::REG_0_3, OK::REG_12_15},
 STORE, MEM_WIDTH::W2, SR_UPDATE::NONE
},
{"ldrd", "ldrd_reg", 0x0e500ff0, 0x000000d0,
 5, {OK::PRED_28_31, OK::REG_PAIR_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::REG_0_3},
 LOAD, MEM_WIDTH::W8, SR_UPDATE::NONE
},
{"strd", "strd_reg", 0x0e500ff0, 0x000000f0,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::REG_0_3, OK::REG_PAIR_12_15},
 STORE, MEM_WIDTH::W8, SR_UPDATE::NONE
},
{"and", "and_regreg", 0x0ff00090, 0x00000010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"and", "and_regimm", 0x0ff00010, 0x00000000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"ands", "ands_regreg", 0x0ff00090, 0x00100010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"ands", "ands_regimm", 0x0ff00010, 0x00100000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"eor", "eor_regreg", 0x0ff00090, 0x00200010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"eor", "eor_regimm", 0x0ff00010, 0x00200000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"eors", "eors_regreg", 0x0ff00090, 0x00300010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"eors", "eors_regimm", 0x0ff00010, 0x00300000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"sub", "sub_regreg", 0x0ff00090, 0x00400010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sub", "sub_regimm", 0x0ff00010, 0x00400000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"subs", "subs_regreg", 0x0ff00090, 0x00500010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"subs", "subs_regimm", 0x0ff00010, 0x00500000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"rsb", "rsb_regreg", 0x0ff00090, 0x00600010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rsb", "rsb_regimm", 0x0ff00010, 0x00600000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rsbs", "rsbs_regreg", 0x0ff00090, 0x00700010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"rsbs", "rsbs_regimm", 0x0ff00010, 0x00700000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"add", "add_regreg", 0x0ff00090, 0x00800010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"add", "add_regimm", 0x0ff00010, 0x00800000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"adds", "adds_regreg", 0x0ff00090, 0x00900010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"adds", "adds_regimm", 0x0ff00010, 0x00900000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"adc", "adc_regreg", 0x0ff00090, 0x00a00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"adc", "adc_regimm", 0x0ff00010, 0x00a00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"adcs", "adcs_regreg", 0x0ff00090, 0x00b00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"adcs", "adcs_regimm", 0x0ff00010, 0x00b00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"sbc", "sbc_regreg", 0x0ff00090, 0x00c00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sbc", "sbc_regimm", 0x0ff00010, 0x00c00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sbcs", "sbcs_regreg", 0x0ff00090, 0x00d00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"sbcs", "sbcs_regimm", 0x0ff00010, 0x00d00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"rsc", "rsc_regreg", 0x0ff00090, 0x00e00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rsc", "rsc_regimm", 0x0ff00010, 0x00e00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rscs", "rscs_regreg", 0x0ff00090, 0x00f00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"rscs", "rscs_regimm", 0x0ff00010, 0x00f00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"orr", "orr_regreg", 0x0ff00090, 0x01800010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"orr", "orr_regimm", 0x0ff00010, 0x01800000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"orrs", "orrs_regreg", 0x0ff00090, 0x01900010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"orrs", "orrs_regimm", 0x0ff00010, 0x01900000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"bic", "bic_regreg", 0x0ff00090, 0x01c00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"bic", "bic_regimm", 0x0ff00010, 0x01c00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"bics", "bics_regreg", 0x0ff00090, 0x01d00010,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"bics", "bics_regimm", 0x0ff00010, 0x01d00000,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"swp", "swp", 0x0ff00ff0, 0x01000090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_0_3, OK::ADDR_BASE_ONLY, OK::REG_16_19},
 ATOMIC, MEM_WIDTH::W4, SR_UPDATE::NONE
},
{"swpb", "swpb", 0x0ff00ff0, 0x01400090,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::REG_0_3, OK::ADDR_BASE_ONLY, OK::REG_16_19},
 ATOMIC, MEM_WIDTH::W1, SR_UPDATE::NONE
},
{"bx", "bx", 0x0ffffff0, 0x012fff10,
 2, {OK::PRED_28_31, OK::REG_0_3},
 JUMP | THUMB, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"blx", "blx_reg", 0x0ffffff0, 0x012fff30,
 2, {OK::PRED_28_31, OK::REG_0_3},
 JUMP | LINK | THUMB, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"clz", "clz", 0x0fff0ff0, 0x016f0f10,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::REG_0_3},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"tst", "tst_regreg", 0x0ff0f090, 0x01100010,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"tst", "tst_regimm", 0x0ff0f010, 0x01100000,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"teq", "teq_regreg", 0x0ff0f090, 0x01300010,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"teq", "teq_regimm", 0x0ff0f010, 0x01300000,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"cmp", "cmp_regreg", 0x0ff0f090, 0x01500010,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"cmp", "cmp_regimm", 0x0ff0f010, 0x01500000,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"cmn", "cmn_regreg", 0x0ff0f090, 0x01700010,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"cmn", "cmn_regimm", 0x0ff0f010, 0x01700000,
 5, {OK::PRED_28_31, OK::REG_16_19, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"mov", "mov_regreg", 0x0fff0090, 0x01a00010,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"mov", "mov_regimm", 0x0fff0010, 0x01a00000,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"movs", "movs_regreg", 0x0fff0090, 0x01b00010,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"movs", "movs_regimm", 0x0fff0010, 0x01b00000,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"mvn", "mvn_regreg", 0x0fff0090, 0x01e00010,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"mvn", "mvn_regimm", 0x0fff0010, 0x01e00000,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"mvns", "mvns_regreg", 0x0fff0090, 0x01f00010,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::REG_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"mvns", "mvns_regimm", 0x0fff0010, 0x01f00000,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_5_6, OK::REG_0_3, OK::IMM_7_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
/* ============================================================*/
/* BLOCK 02000000 */
/* ============================================================*/
{"and", "and_imm", 0x0ff00000, 0x02000000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"ands", "ands_imm", 0x0ff00000, 0x02100000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"eor", "eor_imm", 0x0ff00000, 0x02200000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"eors", "eors_imm", 0x0ff00000, 0x02300000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"sub", "sub_imm", 0x0ff00000, 0x02400000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"subs", "subs_imm", 0x0ff00000, 0x02500000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"rsb", "rsb_imm", 0x0ff00000, 0x02600000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rsbs", "rsbs_imm", 0x0ff00000, 0x02700000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"add", "add_imm", 0x0ff00000, 0x02800000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"adds", "adds_imm", 0x0ff00000, 0x02900000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"adc", "adc_imm", 0x0ff00000, 0x02a00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"adcs", "adcs_imm", 0x0ff00000, 0x02b00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"sbc", "sbc_imm", 0x0ff00000, 0x02c00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sbcs", "sbcs_imm", 0x0ff00000, 0x02d00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"rsc", "rsc_imm", 0x0ff00000, 0x02e00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rscs", "rscs_imm", 0x0ff00000, 0x02f00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"orr", "orr_imm", 0x0ff00000, 0x03800000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"orrs", "orrs_imm", 0x0ff00000, 0x03900000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"bic", "bic_imm", 0x0ff00000, 0x03c00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"bics", "bics_imm", 0x0ff00000, 0x03d00000,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::IMM_0_7_8_11},
 ALU, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"tst", "tst_imm", 0x0ff0f000, 0x03100000,
 3, {OK::PRED_28_31, OK::REG_16_19, OK::IMM_0_7_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"teq", "teq_imm", 0x0ff0f000, 0x03300000,
 3, {OK::PRED_28_31, OK::REG_16_19, OK::IMM_0_7_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"cmp", "cmp_imm", 0x0ff0f000, 0x03500000,
 3, {OK::PRED_28_31, OK::REG_16_19, OK::IMM_0_7_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"cmn", "cmn_imm", 0x0ff0f000, 0x03700000,
 3, {OK::PRED_28_31, OK::REG_16_19, OK::IMM_0_7_8_11},
 TEST, MEM_WIDTH::NA, SR_UPDATE::NCZ
},
{"mov", "mov_imm", 0x0fff0000, 0x03a00000,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::IMM_0_7_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"movs", "movs_imm", 0x0fff0000, 0x03b00000,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::IMM_0_7_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"mvn", "mvn_imm", 0x0fff0000, 0x03e00000,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::IMM_0_7_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"mvns", "mvns_imm", 0x0fff0000, 0x03f00000,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::IMM_0_7_8_11},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NCZ_PSR
},
{"movw", "movw", 0x0ff00000, 0x03000000,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::IMM_0_11_16_19},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"movt", "movt", 0x0ff00000, 0x03400000,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::IMM_0_11_16_19},
 ALU1, MEM_WIDTH::NA, SR_UPDATE::NONE
},
/* ============================================================*/
/* BLOCK 04000000 */
/* ============================================================*/
{"ldp", "ldp_imm", 0xfe50f000, 0xf450f000,
 3, {OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_11},
 PREFETCH, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"ldr", "ldr_imm", 0x0e500000, 0x04100000,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_11},
 LOAD, MEM_WIDTH::W4, SR_UPDATE::NONE
},
{"str", "str_imm", 0x0e500000, 0x04000000,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_11, OK::REG_12_15},
 STORE, MEM_WIDTH::W4, SR_UPDATE::NONE
},
{"ldrb", "ldrb_imm", 0x0e500000, 0x04500000,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_11},
 LOAD, MEM_WIDTH::W1, SR_UPDATE::NONE
},
{"strb", "strb_imm", 0x0e500000, 0x04400000,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::IMM_0_11, OK::REG_12_15},
 STORE, MEM_WIDTH::W1, SR_UPDATE::NONE
},
/* ============================================================*/
/* BLOCK 06000000 */
/* ============================================================*/
{"sdiv", "sdiv", 0x0ff0f0f0, 0x0710f010,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 DIV, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"udiv", "udiv", 0x0ff0f0f0, 0x0730f010,
 4, {OK::PRED_28_31, OK::REG_16_19, OK::REG_0_3, OK::REG_8_11},
 DIV, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"uxtb", "uxtb", 0x0fff03f0, 0x06ef0070,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sxtb", "sxtb", 0x0fff03f0, 0x06af0070,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"uxtab", "uxtab", 0x0ff003f0, 0x06e00070,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sxtab", "sxtab", 0x0ff003f0, 0x06a00070,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"uxtb16", "uxtb16", 0x0fff03f0, 0x06cf0070,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sxtb16", "sxtb16", 0x0fff03f0, 0x068f0070,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"uxtab16", "uxtab16", 0x0ff003f0, 0x06c00070,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sxtab16", "sxtab16", 0x0ff003f0, 0x06800070,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"uxth", "uxth", 0x0fff03f0, 0x06ff0070,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sxth", "sxth", 0x0fff03f0, 0x06bf0070,
 5, {OK::PRED_28_31, OK::REG_12_15, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"uxtah", "uxtah", 0x0ff003f0, 0x06f00070,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"sxtah", "sxtah", 0x0ff003f0, 0x06b00070,
 6, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::SHIFT_MODE_ROT, OK::REG_0_3, OK::IMM_10_11},
 SIGNEXTEND, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rev", "rev", 0x0fff0ff0, 0x06bf0f30,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::REG_0_3},
 BYTEREORDER, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"rev16", "rev16", 0x0fff0ff0, 0x06bf0fb0,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::REG_0_3},
 BYTEREORDER, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"ldp", "ldp_reg", 0xfe50f010, 0xf650f000,
 5, {OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::SHIFT_MODE_5_6_ADDR, OK::REG_0_3, OK::IMM_7_11},
 PREFETCH, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"ldr", "ldr_reg", 0x0e500010, 0x06100000,
 7, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::SHIFT_MODE_5_6_ADDR, OK::REG_0_3, OK::IMM_7_11},
 LOAD, MEM_WIDTH::W4, SR_UPDATE::NONE
},
{"str", "str_reg", 0x0e500010, 0x06000000,
 7, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::SHIFT_MODE_5_6_ADDR, OK::REG_0_3, OK::IMM_7_11, OK::REG_12_15},
 STORE, MEM_WIDTH::W4, SR_UPDATE::NONE
},
{"ldrb", "ldrb_reg", 0x0e500010, 0x06500000,
 7, {OK::PRED_28_31, OK::REG_12_15, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::SHIFT_MODE_5_6_ADDR, OK::REG_0_3, OK::IMM_7_11},
 LOAD, MEM_WIDTH::W1, SR_UPDATE::NONE
},
{"strb", "strb_reg", 0x0e500010, 0x06400000,
 7, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET, OK::REG_16_19, OK::SHIFT_MODE_5_6_ADDR, OK::REG_0_3, OK::IMM_7_11, OK::REG_12_15},
 STORE, MEM_WIDTH::W1, SR_UPDATE::NONE
},
{"ud2", "ud2", 0x0fffffff, 0x07f000f0,
 1, {OK::PRED_28_31},
 MISC, MEM_WIDTH::NA, SR_UPDATE::NONE
},
/* ============================================================*/
/* BLOCK 08000000 */
/* ============================================================*/
{"stm", "stm", 0x0e500000, 0x08000000,
 4, {OK::PRED_28_31, OK::ADDR_MULTI, OK::REG_16_19, OK::REGLIST_0_15},
 STORE | MULTIPLE, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"ldm", "ldm", 0x0e500000, 0x08100000,
 4, {OK::PRED_28_31, OK::REGLIST_0_15, OK::ADDR_MULTI, OK::REG_16_19},
 LOAD | MULTIPLE, MEM_WIDTH::NA, SR_UPDATE::NONE
},
/* ============================================================*/
/* BLOCK 0a000000 */
/* ============================================================*/
{"b", "b", 0x0f000000, 0x0a000000,
 2, {OK::PRED_28_31, OK::SIMM_0_23},
 JUMP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"bl", "bl", 0x0f000000, 0x0b000000,
 3, {OK::PRED_28_31, OK::REG_LINK, OK::SIMM_0_23},
 JUMP | LINK, MEM_WIDTH::NA, SR_UPDATE::NONE
},
/* ============================================================*/
/* BLOCK 0c000000 */
/* ============================================================*/
{"vldr", "vldr_f32", 0x0f300f00, 0x0d100a00,
 5, {OK::PRED_28_31, OK::SREG_12_15_22, OK::ADDR_BASE_WITH_OFFSET2, OK::REG_16_19, OK::IMM_0_7_times4},
 LOAD | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vldr", "vldr_f64", 0x0f300f00, 0x0d100b00,
 5, {OK::PRED_28_31, OK::DREG_12_15_22, OK::ADDR_BASE_WITH_OFFSET2, OK::REG_16_19, OK::IMM_0_7_times4},
 LOAD | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vstr", "vstr_f32", 0x0f300f00, 0x0d000a00,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET2, OK::REG_16_19, OK::IMM_0_7_times4, OK::SREG_12_15_22},
 STORE | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vstr", "vstr_f64", 0x0f300f00, 0x0d000b00,
 5, {OK::PRED_28_31, OK::ADDR_BASE_WITH_OFFSET2, OK::REG_16_19, OK::IMM_0_7_times4, OK::DREG_12_15_22},
 STORE | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmov", "vmov_atof", 0x0ff00fd0, 0x0c400b10,
 4, {OK::PRED_28_31, OK::DREG_0_3_5, OK::REG_12_15, OK::REG_16_19},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmov", "vmov_ftoa", 0x0ff00fd0, 0x0c500b10,
 4, {OK::PRED_28_31, OK::REG_12_15, OK::REG_16_19, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vldm", "vldm_s", 0x0e100f00, 0x0c100a00,
 5, {OK::PRED_28_31, OK::REG_RANGE_0_7, OK::SREG_12_15_22, OK::ADDR_MULTI, OK::REG_16_19},
 LOAD | MULTIPLE | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vldm", "vldm_f", 0x0e100f01, 0x0c100b00,
 5, {OK::PRED_28_31, OK::REG_RANGE_1_7, OK::DREG_12_15_22, OK::ADDR_MULTI, OK::REG_16_19},
 LOAD | MULTIPLE | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vstm", "vstm_s", 0x0e100f00, 0x0c000a00,
 5, {OK::PRED_28_31, OK::ADDR_MULTI, OK::REG_16_19, OK::REG_RANGE_0_7, OK::SREG_12_15_22},
 STORE | MULTIPLE | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vstm", "vstm_f", 0x0e100f01, 0x0c000b00,
 5, {OK::PRED_28_31, OK::ADDR_MULTI, OK::REG_16_19, OK::REG_RANGE_1_7, OK::DREG_12_15_22},
 STORE | MULTIPLE | VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
/* ============================================================*/
/* BLOCK 0e000000 */
/* ============================================================*/
{"svc", "svc", 0x0f000000, 0x0f000000,
 2, {OK::PRED_28_31, OK::IMM_0_23},
 SYSCALL, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmov", "vmov_atos", 0x0ff00f7f, 0x0e000a10,
 3, {OK::PRED_28_31, OK::SREG_16_19_7, OK::REG_12_15},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmov", "vmov_stoa", 0x0ff00f7f, 0x0e100a10,
 3, {OK::PRED_28_31, OK::REG_12_15, OK::SREG_16_19_7},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.f32.f64", "vcvt_f32_f64", 0x0fbf0fd0, 0x0eb70bc0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.f64.f32", "vcvt_f64_f32", 0x0fbf0fd0, 0x0eb70ac0,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.s32.f64", "vcvt_s32_f64", 0x0fbf0fd0, 0x0ebd0bc0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.s32.f32", "vcvt_s32_f32", 0x0fbf0fd0, 0x0ebd0ac0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.u32.f64", "vcvt_u32_f64", 0x0fbf0fd0, 0x0ebc0bc0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.u32.f32", "vcvt_u32_f32", 0x0fbf0fd0, 0x0ebc0ac0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.f64.s32", "vcvt_f64_s32", 0x0fbf0fd0, 0x0eb80bc0,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.f32.s32", "vcvt_f32_s32", 0x0fbf0fd0, 0x0eb80ac0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.f64.u32", "vcvt_f64_u32", 0x0fbf0fd0, 0x0eb80b40,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcvt.f32.u32", "vcvt_f32_u32", 0x0fbf0fd0, 0x0eb80a40,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmp.f32", "vcmp_f32", 0x0fbf0fd0, 0x0eb40a40,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmp.f64", "vcmp_f64", 0x0fbf0fd0, 0x0eb40b40,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmp.f32", "vcmp_f32_zero", 0x0fbf0fff, 0x0eb50a40,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::IMM_ZERO},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmp.f64", "vcmp_f64_zero", 0x0fbf0fff, 0x0eb50b40,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::IMM_ZERO},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmpe.f32", "vcmpe_f32", 0x0fbf0fd0, 0x0eb40ac0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmpe.f64", "vcmpe_f64", 0x0fbf0fd0, 0x0eb40bc0,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmpe.f32", "vcmpe_f32_zero", 0x0fbf0fff, 0x0eb50ac0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::IMM_ZERO},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vcmpe.f64", "vcmpe_f64_zero", 0x0fbf0fff, 0x0eb50bc0,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::IMM_ZERO},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vabs.f32", "vabs_f32", 0x0fbf0fd0, 0x0eb00ac0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vabs.f64", "vabs_f64", 0x0fbf0fd0, 0x0eb00bc0,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmov.f32", "vmov_f32", 0x0fbf0fd0, 0x0eb00a40,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmov.f64", "vmov_f64", 0x0fbf0fd0, 0x0eb00b40,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vsqrt.f32", "vsqrt_f32", 0x0fbf0fd0, 0x0eb10ac0,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vsqrt.f64", "vsqrt_f64", 0x0fbf0fd0, 0x0eb10bc0,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vneg.f32", "vneg_f32", 0x0fbf0fd0, 0x0eb10a40,
 3, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vneg.f64", "vneg_f64", 0x0fbf0fd0, 0x0eb10b40,
 3, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vdiv.f32", "vdiv_f32", 0x0fb00f50, 0x0e800a00,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vdiv.f64", "vdiv_f64", 0x0fb00f50, 0x0e800b00,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmul.f32", "vmul_f32", 0x0fb00f50, 0x0e200a00,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmul.f64", "vmul_f64", 0x0fb00f50, 0x0e200b00,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vadd.f32", "vadd_f32", 0x0fb00f50, 0x0e300a00,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vadd.f64", "vadd_f64", 0x0fb00f50, 0x0e300b00,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vsub.f32", "vsub_f32", 0x0fb00f50, 0x0e300a40,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vsub.f64", "vsub_f64", 0x0fb00f50, 0x0e300b40,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vnmul.f32", "vnmul_f32", 0x0fb00f50, 0x0e200a40,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vnmul.f64", "vnmul_f64", 0x0fb00f50, 0x0e200b40,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vnmls.f32", "vnmls_f32", 0x0fb00f50, 0x0e100a00,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vnmls.f64", "vnmls_f64", 0x0fb00f50, 0x0e100b00,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vnmla.f32", "vnmla_f32", 0x0fb00f50, 0x0e100a40,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vnmla.f64", "vnmla_f64", 0x0fb00f50, 0x0e100b40,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmls.f32", "vmls_f32", 0x0fb00f50, 0x0e000a40,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmls.f64", "vmls_f64", 0x0fb00f50, 0x0e000b40,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmla.f32", "vmla_f32", 0x0fb00f50, 0x0e000a00,
 4, {OK::PRED_28_31, OK::SREG_12_15_22, OK::SREG_16_19_7, OK::SREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmla.f64", "vmla_f64", 0x0fb00f50, 0x0e000b00,
 4, {OK::PRED_28_31, OK::DREG_12_15_22, OK::DREG_16_19_7, OK::DREG_0_3_5},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NONE
},
{"vmrs", "vmrs_APSR_nzcv_fpscr", 0x0fffffff, 0x0ef1fa10,
 1, {OK::PRED_28_31},
 VFP, MEM_WIDTH::NA, SR_UPDATE::NCZV
},
};

const int16_t OpcodeTableJumper[] = {
1, 96,
97, 126,
127, 131,
132, 153,
154, 155,
156, 157,
158, 167,
168, 215
};

// Indexed by FieldKind
static const Field FieldTable[] = {
{   // Invalid = 0
    0, {
}}, 
{   // REG_0_3 = 1
    1, {
    {BitRangeKind::Verbatim, 4, 0},
}}, 
{   // REG_8_11 = 2
    1, {
    {BitRangeKind::Verbatim, 4, 8},
}}, 
{   // REG_12_15 = 3
    1, {
    {BitRangeKind::Verbatim, 4, 12},
}}, 
{   // REG_16_19 = 4
    1, {
    {BitRangeKind::Verbatim, 4, 16},
}}, 
{   // REG_LINK = 5
    1, {
    {BitRangeKind::Force14, 0, 0},
}}, 
{   // REG_PAIR_12_15 = 6
    1, {
    {BitRangeKind::Verbatim, 4, 12},
}}, 
{   // DREG_0_3_5 = 7
    2, {
    {BitRangeKind::Hi, 1, 5},
    {BitRangeKind::Lo, 4, 0},
}}, 
{   // DREG_12_15_22 = 8
    2, {
    {BitRangeKind::Hi, 1, 22},
    {BitRangeKind::Lo, 4, 12},
}}, 
{   // DREG_16_19_7 = 9
    2, {
    {BitRangeKind::Hi, 1, 7},
    {BitRangeKind::Lo, 4, 16},
}}, 
{   // SREG_0_3_5 = 10
    2, {
    {BitRangeKind::Hi, 4, 0},
    {BitRangeKind::Lo, 1, 5},
}}, 
{   // SREG_12_15_22 = 11
    2, {
    {BitRangeKind::Hi, 4, 12},
    {BitRangeKind::Lo, 1, 22},
}}, 
{   // SREG_16_19_7 = 12
    2, {
    {BitRangeKind::Hi, 4, 16},
    {BitRangeKind::Lo, 1, 7},
}}, 
{   // SHIFT_MODE_5_6 = 13
    1, {
    {BitRangeKind::Verbatim, 2, 5},
}}, 
{   // SHIFT_MODE_5_6_ADDR = 14
    1, {
    {BitRangeKind::Verbatim, 2, 5},
}}, 
{   // SHIFT_MODE_ROT = 15
    1, {
    {BitRangeKind::Force3, 0, 0},
}}, 
{   // REGLIST_0_15 = 16
    1, {
    {BitRangeKind::Verbatim, 16, 0},
}}, 
{   // REG_RANGE_0_7 = 17
    1, {
    {BitRangeKind::Verbatim, 8, 0},
}}, 
{   // REG_RANGE_1_7 = 18
    1, {
    {BitRangeKind::Verbatim, 7, 1},
}}, 
{   // PRED_28_31 = 19
    1, {
    {BitRangeKind::Verbatim, 4, 28},
}}, 
{   // ADDR_BASE_ONLY = 20
    1, {
    {BitRangeKind::Force6, 0, 0},
}}, 
{   // ADDR_BASE_WITH_OFFSET = 21
    3, {
    {BitRangeKind::P, 1, 24},
    {BitRangeKind::U, 1, 23},
    {BitRangeKind::W, 1, 21},
}}, 
{   // ADDR_BASE_WITH_OFFSET2 = 22
    1, {
    {BitRangeKind::Times2Plus4, 1, 23},
}}, 
{   // ADDR_MULTI = 23
    3, {
    {BitRangeKind::P, 1, 24},
    {BitRangeKind::U, 1, 23},
    {BitRangeKind::W, 1, 21},
}}, 
{   // IMM_0_7_times4 = 24
    1, {
    {BitRangeKind::Times4, 8, 0},
}}, 
{   // IMM_0_11 = 25
    1, {
    {BitRangeKind::Verbatim, 12, 0},
}}, 
{   // IMM_0_3_8_11 = 26
    2, {
    {BitRangeKind::Hi, 4, 8},
    {BitRangeKind::Lo, 4, 0},
}}, 
{   // IMM_7_11 = 27
    1, {
    {BitRangeKind::Verbatim, 5, 7},
}}, 
{   // IMM_10_11 = 28
    1, {
    {BitRangeKind::Times8, 2, 10},
}}, 
{   // IMM_0_23 = 29
    1, {
    {BitRangeKind::Verbatim, 24, 0},
}}, 
{   // IMM_0_7_8_11 = 30
    1, {
    {BitRangeKind::Rotated, 12, 0},
}}, 
{   // IMM_ZERO = 31
    1, {
    {BitRangeKind::Force0, 0, 0},
}}, 
{   // IMM_0_11_16_19 = 32
    2, {
    {BitRangeKind::Hi, 4, 16},
    {BitRangeKind::Lo, 12, 0},
}}, 
{   // SIMM_0_23 = 33
    1, {
    {BitRangeKind::Signed, 24, 0},
}}, 
};

// Indexed by djb2 hash of mnemonic. Collisions are resolved via linear probing
static const OPC MnemonicHashTable[512] = {
   OPC::tst_regimm, OPC::invalid, OPC::subs_regimm, OPC::adcs_imm,
   OPC::subs_imm, OPC::vcmp_f32, OPC::vcmp_f32_zero, OPC::b,
   OPC::rsc_regreg, OPC::blx_reg, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::vsub_f32,
   OPC::vcvt_f64_u32, OPC::invalid, OPC::invalid, OPC::mul,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::sbc_regreg, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::swpb, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::smulls, OPC::bics_regimm, OPC::cmp_imm,
   OPC::vldr_f32, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ands_imm, OPC::rsb_imm, OPC::uxtb16,
   OPC::sxtab16, OPC::sub_imm, OPC::vsqrt_f32, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::vmov_f64, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::adds_regimm, OPC::rscs_imm, OPC::vcvt_f64_f32,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::ldr_imm, OPC::sub_regreg, OPC::vcmpe_f32,
   OPC::invalid, OPC::orrs_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::sbcs_imm, OPC::invalid,
   OPC::invalid, OPC::bic_imm, OPC::invalid, OPC::invalid,
   OPC::mvn_imm, OPC::rev16, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::vmov_stoa,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::vcmp_f64, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::clz, OPC::adc_imm,
   OPC::invalid, OPC::teq_imm, OPC::vmls_f32, OPC::invalid,
   OPC::umull, OPC::vsub_f64, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::strex,
   OPC::adcs_regreg, OPC::sdiv, OPC::invalid, OPC::rsbs_regimm,
   OPC::cmp_regreg, OPC::vnmls_f32, OPC::ldp_reg, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::eor_regreg, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::teq_regreg, OPC::ldrb_imm,
   OPC::vldr_f64, OPC::adc_regimm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::vmul_f32,
   OPC::vsqrt_f64, OPC::invalid, OPC::smlabb, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::vnmul_f32, OPC::invalid, OPC::adds_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::smlabt, OPC::add_regreg, OPC::bics_imm, OPC::movt,
   OPC::vcvt_u32_f32, OPC::vcvt_f32_s32, OPC::movw, OPC::rsc_imm,
   OPC::vcmpe_f64, OPC::invalid, OPC::invalid, OPC::and_regreg,
   OPC::bic_regimm, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::rscs_regreg,
   OPC::invalid, OPC::invalid, OPC::cmn_regreg, OPC::sbc_imm,
   OPC::umlal, OPC::vneg_f32, OPC::tst_imm, OPC::strb_imm,
   OPC::ldrsh_imm, OPC::invalid, OPC::ands_regreg, OPC::invalid,
   OPC::ldrd_reg, OPC::invalid, OPC::smulbb, OPC::sbcs_regreg,
   OPC::ldrh_reg, OPC::rsc_regimm, OPC::movs_imm, OPC::vadd_f32,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::orr_regreg,
   OPC::invalid, OPC::invalid, OPC::vmls_f64, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::str_reg,
   OPC::smulbt, OPC::sbc_regimm, OPC::invalid, OPC::mla,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::ldrex, OPC::mvns_regreg, OPC::muls, OPC::orrs_regreg,
   OPC::smlatb, OPC::sxtb, OPC::uxtab, OPC::vnmls_f64,
   OPC::sxth, OPC::sxtb16, OPC::vcmpe_f64_zero, OPC::uxtah,
   OPC::add_imm, OPC::mls, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::vmul_f64, OPC::ldrsb_reg, OPC::smlatt, OPC::eors_regreg,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::strd_reg,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::strh_reg,
   OPC::invalid, OPC::movs_regreg, OPC::vnmul_f64, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::mvns_imm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::sub_regimm,
   OPC::vcvt_u32_f64, OPC::mvn_regreg, OPC::mov_regreg, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::vabs_f32,
   OPC::smultb, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::vneg_f64, OPC::cmn_imm, OPC::invalid, OPC::rsb_regreg,
   OPC::invalid, OPC::vcvt_s32_f32, OPC::invalid, OPC::vcvt_f32_u32,
   OPC::invalid, OPC::invalid, OPC::smultt, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::mlas, OPC::umlals,
   OPC::vadd_f64, OPC::vstm_f, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::and_imm, OPC::tst_regreg,
   OPC::invalid, OPC::subs_regreg, OPC::udiv, OPC::invalid,
   OPC::eors_imm, OPC::adcs_regimm, OPC::vstm_s, OPC::invalid,
   OPC::invalid, OPC::cmp_regimm, OPC::invalid, OPC::ldp_imm,
   OPC::vdiv_f32, OPC::invalid, OPC::invalid, OPC::eor_regimm,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::teq_regimm,
   OPC::invalid, OPC::invalid, OPC::rev, OPC::bl,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::orr_imm, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::bx,
   OPC::vmla_f32, OPC::bics_regreg, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::umulls,
   OPC::invalid, OPC::vcmpe_f32_zero, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::vnmla_f32, OPC::add_regimm, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::smull, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::vmov_ftoa, OPC::invalid,
   OPC::and_regimm, OPC::stm, OPC::invalid, OPC::invalid,
   OPC::adds_regreg, OPC::invalid, OPC::vstr_f32, OPC::vmrs_APSR_nzcv_fpscr,
   OPC::rscs_regimm, OPC::vabs_f64, OPC::invalid, OPC::cmn_regimm,
   OPC::ldr_reg, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::vcmp_f64_zero, OPC::invalid, OPC::ands_regimm,
   OPC::invalid, OPC::ldrd_imm, OPC::vcvt_s32_f64, OPC::vcvt_f64_s32,
   OPC::sbcs_regimm, OPC::ldrh_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::vmov_atof, OPC::invalid,
   OPC::orr_regimm, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::vldm_f, OPC::invalid, OPC::invalid,
   OPC::str_imm, OPC::rsbs_imm, OPC::ldm, OPC::vmov_atos,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::uxtb, OPC::mvns_regimm, OPC::vldm_s, OPC::orrs_regimm,
   OPC::invalid, OPC::vdiv_f64, OPC::uxth, OPC::invalid,
   OPC::uxtab16, OPC::ud2, OPC::svc, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::rsbs_regreg, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::smlal, OPC::ldrsb_imm,
   OPC::eors_regimm, OPC::vcvt_f32_f64, OPC::invalid, OPC::invalid,
   OPC::strd_imm, OPC::vmla_f64, OPC::ldrb_reg, OPC::invalid,
   OPC::strh_imm, OPC::adc_regreg, OPC::movs_regimm, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::vnmla_f64, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::mvn_regimm, OPC::mov_regimm,
   OPC::vmov_f32, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::swp,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::vstr_f64,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::sxtab,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::rsb_regimm, OPC::eor_imm, OPC::bic_regreg, OPC::sxtah,
   OPC::invalid, OPC::smlals, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::invalid, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::mov_imm, OPC::invalid, OPC::invalid,
   OPC::invalid, OPC::strb_reg, OPC::invalid, OPC::ldrsh_reg,
};


const char* const PRED_ToStringMap[] = {
    "eq", // 0
    "ne", // 1
    "cs", // 2
    "cc", // 3
    "mi", // 4
    "pl", // 5
    "vs", // 6
    "vc", // 7
    "hi", // 8
    "ls", // 9
    "ge", // 10
    "lt", // 11
    "gt", // 12
    "le", // 13
    "al", // 14
    "invalid_pred", // 15
};

template<>  // template specialization for PRED
const char* EnumToString<PRED>(PRED x) { return PRED_ToStringMap[unsigned(x)]; }


const char* const ADDR_MODE_ToStringMap[] = {
    "puw", // 0
    "puW", // 1
    "pUw", // 2
    "pUW", // 3
    "Puw", // 4
    "PuW", // 5
    "PUw", // 6
    "PUW", // 7
};

template<>  // template specialization for ADDR_MODE
const char* EnumToString<ADDR_MODE>(ADDR_MODE x) { return ADDR_MODE_ToStringMap[unsigned(x)]; }


const char* const SHIFT_ToStringMap[] = {
    "lsl", // 0
    "lsr", // 1
    "asr", // 2
    "ror_rrx", // 3
};

template<>  // template specialization for SHIFT
const char* EnumToString<SHIFT>(SHIFT x) { return SHIFT_ToStringMap[unsigned(x)]; }

/* @AUTOGEN-END@ */

const Opcode* FindArmOpcode(uint32_t bit_value) {
  uint32_t discriminant = (bit_value & 0x0e000000) >> 25;
  const int start = OpcodeTableJumper[2 * discriminant];
  const int end = OpcodeTableJumper[2 * discriminant + 1];
  if (start >= 0) {
    for (int i = start; i <= end; ++i) {
      const struct Opcode* opc = &OpcodeTable[i];
      if ((opc->bit_mask & bit_value) == opc->bit_value) {
        return opc;
      }
    }
  }
  return nullptr;
}

uint32_t DecodeRotatedImm(uint32_t data) {
  uint32_t x = data & 0xff;
  uint32_t rot = (data & 0xf00) >> 7;
  uint32_t mask = (1 << rot) - 1;
  return (x >> rot) | ((x & mask) << (32 - rot));
}

// Inverse of DecodeRotatedImm()
// returns -1 in case of failure
int32_t EncodeRotatedImm(int32_t immediate) {
  uint32_t x = immediate;
  for (int r = 0; r < 16; ++r) {
    if ((x & 0xff) == x) {
      return (r << 8) | x;
    }
    // rotate left by 2
    x = (x << 2) | (x >> 30);
  }
  return -1;
}

int32_t DecodeOperand(uint32_t data, OK field_kind) {
  const BitRange* bit_ranges = FieldTable[uint8_t(field_kind)].bit_ranges;

  int32_t hi = 0;
  for (unsigned i = 0; i < FieldTable[uint8_t(field_kind)].num_bit_ranges;
       ++i) {
    const BitRange* range = bit_ranges + i;
    uint32_t mask = (1 << range->width) - 1;
    uint32_t x = (data >> range->position) & mask;
    switch (range->modifier) {
      case BitRangeKind::Verbatim:
        return x;
      case BitRangeKind::Times8:
        return x << 3;
      case BitRangeKind::Times4:
        return x << 2;
      case BitRangeKind::Times2:
        return x << 1;
      case BitRangeKind::Times2Plus4:
        return (x << 1) + 4;
      case BitRangeKind::Force0:
        return 0;
      case BitRangeKind::Force1:
        return 1;
      case BitRangeKind::Force3:
        return 3;
      case BitRangeKind::Force6:
        return 6;
      case BitRangeKind::Force14:
        return 14;
      case BitRangeKind::P:
      case BitRangeKind::Hi:  // hi must directly precede lo
        hi = x;
        continue;  // SKIP
      case BitRangeKind::U:
        hi = x | hi << range->width;
        continue;
      case BitRangeKind::W:
      case BitRangeKind::Lo:
        return x | hi << range->width;
      case BitRangeKind::Rotated:
        return DecodeRotatedImm(x);
      case BitRangeKind::Signed: {
        uint32_t mask2 = mask >> 1;
        if ((x & mask2) != x) {  // hi bit set
          x -= 1 << range->width;
        }
        return x;
      }
    }
  }
  ASSERT(false, "unreachable");
  return 0;
}

void EncodeOperand(int32_t x,
                   const struct Field* field,
                   uint32_t* bits_value,
                   uint32_t* bits_mask) {
  const BitRange* bit_ranges = field->bit_ranges;
  int32_t hi = 0;
  // backwards is important
  for (int i = field->num_bit_ranges - 1; i >= 0; --i) {
    const BitRange* range = bit_ranges + i;
    const uint32_t mask = (1 << range->width) - 1;
    switch (range->modifier) {
      case BitRangeKind::Verbatim:
        // assert (0);
        break;
      case BitRangeKind::Times8:
        ASSERT((x & 7) == 0, "");
        x >>= 3;
        break;
      case BitRangeKind::Times4:
        ASSERT((x & 3) == 0, "");
        x >>= 2;
        break;
      case BitRangeKind::Times2:
        ASSERT((x & 1) == 0, "");
        x >>= 1;
        break;
      case BitRangeKind::Times2Plus4:
        ASSERT((x & 1) == 0, "");
        ASSERT((x & 4) == 4, "");
        x = (x >> 1) & 1;
        break;
      case BitRangeKind::Force0:
        ASSERT(x == 0, "");
        continue;
      case BitRangeKind::Force1:
        ASSERT(x == 1, "");
        continue;
      case BitRangeKind::Force3:
        ASSERT(x == 3, "");
        continue;
      case BitRangeKind::Force6:
        ASSERT(x == 6, "");
        continue;
      case BitRangeKind::Force14:
        ASSERT(x == 14, "");
        continue;
      case BitRangeKind::P:
      case BitRangeKind::Hi:  // hi will process directly after low (reverse for loop)
        x = hi;
        break;
      case BitRangeKind::U:
        x = hi & mask;
        hi >>= range->width;
        break;
      case BitRangeKind::Lo:
      case BitRangeKind::W:
        hi = x >> range->width;
        x &= mask;
        break;
      case BitRangeKind::Rotated:
        x = EncodeRotatedImm(x);
        ASSERT((x & 0xfff) == x, "");
        break;
      case BitRangeKind::Signed: {
        if (x >= 0) {
          ASSERT((x & int32_t(mask >> 1)) == x, "bad val " << x);
        } else {
          ASSERT((x | int32_t(mask >> 1)) == ~0, "");
        }
        x &= mask;
        break;
      }
    }
    ASSERT((int32_t(mask) & x) == x, "bad value - did you forget the pred");
    ASSERT(((mask << range->position) & *bits_mask) == 0, "");
    *bits_mask |= mask << range->position;
    *bits_value |= x << range->position;
  }
}

bool DecodeIns(Ins* ins, uint32_t data) {
  const struct Opcode* opcode = FindArmOpcode(data);
  if (opcode == nullptr) return false;

  ins->opcode = opcode;
  for (unsigned i = 0; i < opcode->num_fields; ++i) {
    ins->operands[i] = DecodeOperand(data, opcode->fields[i]);
  }
  return true;
}

uint32_t EncodeIns(const Ins& ins) {
  const Opcode* opcode = ins.opcode;
  uint32_t value = opcode->bit_value;
  uint32_t mask = opcode->bit_mask;
  for (unsigned i = 0; i < opcode->num_fields; ++i) {
    const OK kind = ins.opcode->fields[i];
    ASSERT(kind != OK::Invalid, "");
    EncodeOperand(ins.operands[i], &FieldTable[uint8_t(kind)], &value,
                  &mask);
  }
  ASSERT(mask == 0xffffffff, "problems encoding " << opcode->name);
  return value;
}

const Opcode* FindArmOpcodeForMnemonic(std::string_view s) {
  uint32_t h = 5381;
  for (uint8_t c : s) {
    h = (h << 5) + h + c;
  }
  h &= 0xffff;

  for (uint32_t d = 0; d < 512; ++d) {
    OPC opc = MnemonicHashTable[(h + d) % 512];
    if (opc == OPC::invalid) return nullptr;
    auto* opcode = &OpcodeTable[uint32_t(opc)];
    if (opcode->enum_name == s) return opcode;
  }
  return nullptr;
}

}  // namespace cwerg::a32
