#
name: cwerg-tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    # Ubuntu 26.04 is not available
    #runs-on: ${{ matrix.os }}
    # strategy:
    #  matrix:
    #    python-version: [3.12.4]
    #    os: [ubuntu-24.04]
    #    #python-version: [3.7, 3.8, 3.9]
    #    #os: [ubuntu-latest, macos-latest, windows-latest]
    container:
      image: ubuntu:26.04
    steps:
    - uses: actions/checkout@v6
    - name: Install OS Deps
      run: |
        apt update
        apt -y install lsb-release
    - name: OS Version Summary
      run: |
        uname -a
        echo
        lsb_release -a
    - name: Install Toolchain Deps
      run: |
        apt -y install time make cmake python3 gcc g++ cloc qemu-user-binfmt
        echo
        apt -y install libunwind-dev gcc-multilib
        echo
        apt -y install gcc-arm-linux-gnueabihf  g++-arm-linux-gnueabihf
        apt -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    - name: Toolchain Version Summary
      run: |
        PYPY=python3 CC=gcc CXX=g++ MAKESILENT='' make show_versions
    - name: Run Tests
      run: |
        PYPY=python3 CC=gcc CXX=g++ MAKESILENT='' make tests
    - name: Benchmark
      run: |
        PYPY=python3 CC=clang CXX=clang++ MAKESILENT='' make benchmark
